const std = @import("std");

pub const Conn = @This();

fd: std.posix.socket_t,
// application's intention, for the event loop
want_read: bool,
want_write: bool,
want_close: bool,
// buffered input and output
// data to be parsed by the application
incoming: []u8,
// responses generated by the application
outgoing: []u8,
